# Generated by Django 5.2 on 2025-04-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='id_ciudad',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
