# Generated by Django 5.2 on 2025-04-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0002_remove_ciudad_id_ciudad_ciudad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='id_departamento',
            new_name='departamento',
        ),
    ]
