# Generated by Django 5.2 on 2025-04-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0003_rename_id_departamento_ciudad_departamento'),
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='pais.pais'),
            preserve_default=False,
        ),
    ]
