# Generated by Django 5.2 on 2025-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_persona_id_persona_id_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id_persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
