# Generated by Django 5.2 on 2025-04-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_persona_id_persona_persona_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
    ]
