# Generated by Django 5.2 on 2025-04-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_persona_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table=None,
        ),
    ]
