# Generated by Django 5.2 on 2025-04-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0004_ciudad_pais'),
        ('persona', '0005_alter_persona_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacidos_en', to='ciudad.ciudad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes_en', to='ciudad.ciudad'),
        ),
    ]
