# Generated by Django 5.2 on 2025-04-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0004_ciudad_pais'),
        ('persona', '0006_persona_ciudad_nacimiento_persona_ciudad_residencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ciudad_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ciudad_residencia',
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad_id_nacimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacimientos', to='ciudad.ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad_id_residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencias', to='ciudad.ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sisben',
            field=models.CharField(max_length=20),
        ),
    ]
