# Generated by Django 5.2 on 2025-04-06 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0004_ciudad_pais'),
        ('persona', '0007_remove_persona_ciudad_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacidos_en', to='ciudad.ciudad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ciudad_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes_en', to='ciudad.ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad_id_nacimiento',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='ciudad_id_residencia',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='sisben',
            field=models.CharField(max_length=50),
        ),
    ]
