# Generated by Django 5.2 on 2025-04-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_persona_ciudad_nacimiento_persona_ciudad_residencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ciudad_id_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ciudad_id_residencia',
        ),
    ]
